//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AplikacjaWindows
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ceny
    {
        public int Id { get; set; }
	    [Required]
		public Nullable<int> CennikId { get; set; }
	    [Required]
		public Nullable<int> TowarId { get; set; }
	    [Required]
		[Range(0.01,10000000000000000000)]
		public decimal Cena { get; set; }
	    [Required]
		[Range(0,100)]
        public Nullable<decimal> Rabat { get; set; }
		[NotMapped]
        public virtual Cenniki Cenniki { get; set; }
	    [NotMapped]
		public virtual Towary Towary { get; set; }
    }
}
