//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacjaWindows
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TowaryDBEntities : DbContext
    {
        public TowaryDBEntities()
            : base("name=TowaryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cenniki> Cennikis { get; set; }
        public virtual DbSet<Ceny> Cenies { get; set; }
        public virtual DbSet<Towary> Towaries { get; set; }
    }
}
