//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacjaWindows
{
    using System;
    using System.Collections.Generic;
    
    public partial class Towary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Towary()
        {
            this.Cenies = new HashSet<Ceny>();
        }
    
        public int Id { get; set; }
        public string Kod { get; set; }
        public string Nazwa { get; set; }
        public Nullable<decimal> Masa { get; set; }
        public string JM { get; set; }
	    public Nullable<System.DateTime> Data_Utworzenia { get; set; } = DateTime.Now;
        public Nullable<System.DateTime> Data_Modyfikacji { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ceny> Cenies { get; set; }
    }
}
